name: Testing
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Deprecation warning'
        run: |
          echo "This GHA is deprecated, please re-run plone.meta on your repository"
          echo "If you are still relying on this jobs, "
          echo "please create an issue in https://github.com/plone/meta/issues/new"
          exit 1
