name: 'Setup Frontend Codebase'
description: 'Setup and install a frontend codebase'

inputs:
  node-version:
    description: 'Node Version'
    required: true
    default: '22.x'
  working-directory:
    description: 'Working directory to use'
    required: false
    default: '.'
  cache:
    description: 'Cache type to use'
    required: false
    default: 'pnpm'
  cache-dependency-path:
    description: 'Cache dependency path'
    required: false
    default: '**/pnpm-lock.yaml'

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6.4.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable corepack
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        npm i -g corepack@latest
        corepack enable
        corepack prepare --activate

    - name: Cache for node version ${{ inputs.node-version }}
      uses: actions/setup-node@v6.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: '${{ inputs.cache }}'
        cache-dependency-path: '${{ inputs.cache-dependency-path }}'

    - name: Install project dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: make install
