name: "Lint Python codebase"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      plone-version:
        required: true
        type: string
      working-directory:
        required: false
        default: '.'
        type: string
      check-typing:
        default: false
        type: boolean
      version-ruff:
        required: false
        default: 'latest'
        type: string
      version-zpretty:
        required: false
        default: 'latest'
        type: string
      version-pyroma:
        required: false
        default: 'latest'
        type: string
      version-check-python:
        required: false
        default: 'latest'
        type: string
      zpretty-check-path:
        required: false
        default: 'src'
        type: string
      zpretty-options:
        required: false
        default: ''
        type: string

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    env:
      PYTHON_VERSION: ${{ inputs.python-version }}
      PLONE_VERSION: ${{ inputs.plone-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup codebase
        uses: plone/meta/.github/actions/setup_backend_uv@2.x
        with:
          python-version: ${{ inputs.python-version }}
          plone-version: ${{ inputs.plone-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Check formatting
        if: ${{ success() || failure() }}
        id: ruff-format
        shell: bash
        run: |
          uvx ruff@${INPUTS_VERSION_RUFF} format --diff
        env:
          INPUTS_VERSION_RUFF: ${{ inputs.version-ruff }}

      - name: Check lint
        if: ${{ success() || failure() }}
        id: ruff-lint
        shell: bash
        run: |
          uvx ruff@${INPUTS_VERSION_RUFF} check --diff
        env:
          INPUTS_VERSION_RUFF: ${{ inputs.version-ruff }}

      - name: Check XML / ZCML
        if: ${{ success() || failure() }}
        id: zpretty
        shell: bash
        run: |
          uvx zpretty@${INPUTS_VERSION_ZPRETTY} --check ${INPUTS_ZPRETTY_CHECK_PATH} ${INPUTS_ZPRETTY_OPTIONS}
        env:
          INPUTS_VERSION_ZPRETTY: ${{ inputs.version-zpretty }}
          INPUTS_ZPRETTY_CHECK_PATH: ${{ inputs.zpretty-check-path }}
          INPUTS_ZPRETTY_OPTIONS: ${{ inputs.zpretty-options }}

      - name: Check Package Metadata
        if: ${{ success() || failure() }}
        id: pyroma
        shell: bash
        run: |
          uvx pyroma@${INPUTS_VERSION_PYROMA} -d .
        env:
          INPUTS_VERSION_PYROMA: ${{ inputs.version-pyroma }}

      - name: Check Python Versions
        if: ${{ success() || failure() }}
        id: py-versions
        shell: bash
        run: |
          uvx check-python-versions@${INPUTS_VERSION_CHECK_PYTHON} .
        env:
          INPUTS_VERSION_CHECK_PYTHON: ${{ inputs.version-check-python }}

      - name: Check typing
        if: ${{ (success() || failure()) && inputs.check-typing }}
        id: typing
        run: |
          uv run mypy src

      - name: Report
        if: ${{ success() || failure() }}
        run: |
          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| Format | ${{ steps.ruff-format.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Lint | ${{ steps.ruff-lint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| XML / ZCML | ${{ steps.zpretty.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Package Metadata | ${{ steps.pyroma.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Python Versions | ${{ steps.py-versions.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Typing | ${{ steps.typing.conclusion == 'failure' && '❌' || steps.typing.conclusion == 'skipped' && '⏭️' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
