# Workflow meant to be used by external repositories
# that are configured with this `meta` repository
name: Coverage
on:
  # allow this workflow to be called
  # by other workflows from other repositories
  workflow_call:
    inputs:
      os-packages:
        required: false
        type: string

jobs:
  test:
    name: Coverage report
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv + caching
        uses: astral-sh/setup-uv@v7.5.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            setup.*
            tox.ini
            pyproject.toml
          python-version: ${{ matrix.python-version }}
      - name: install OS packages
        if: inputs.os-packages != ''
        run: sudo apt-get install -y ${{ inputs.os-packages }}
      - name: Initialize tox
        run: |
          if [ `uvx tox list --no-desc -f init|wc -l` = 1 ]; then uvx --with tox-uv tox -e init;else true; fi
      - name: Run coverage
        run: |
          uvx --with tox-uv tox -e coverage >> $GITHUB_STEP_SUMMARY
