name: Unit tests
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
      working-directory:
        type: string
        required: false
        default: '.'

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Main checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: plone/meta/.github/actions/setup_uv@2.x
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Setup codebase
        uses: plone/meta/.github/actions/setup_frontend@2.x
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Unit tests
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: |
          make ci-test
