name: CI
on: [push]

jobs:
  qa:
    name: QA report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv + caching
        uses: astral-sh/setup-uv@v7.5.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            tox.ini
            pyproject.toml
          python-version: ${{ matrix.python-version }}
      - name: Run QA tools
        run: uvx tox -e lint

  test:
    name: Tests / py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv + caching
        uses: astral-sh/setup-uv@v7.5.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            tox.ini
            pyproject.toml
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uvx tox -e test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv + caching
        uses: astral-sh/setup-uv@v7.5.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            tox.ini
            pyproject.toml
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uvx tox -e coverage
