# Workflow meant to be used by external repositories
# that are configured with this `meta` repository
name: Release status
on:
  # allow this workflow to be called
  # by other workflows from other repositories
  workflow_call:

jobs:
  test:
    name: Release status
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: ["ubuntu-latest"]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: uv pip install tox tox-uv
      - name: Initialize tox
        run: |
          if [ `tox list --no-desc -f init|wc -l` = 1 ]; then tox -e init;else true; fi
      - name: Check release status
        run: |
          tox -e release-check
